receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

exporters:
  otlp:
    endpoint: "100.102.32.69:4320"
    tls: 
      insecure: true
  
  prometheus:
    endpoint: "0.0.0.0:8889" 

  logging:
    loglevel: debug

  otlphttp:
    endpoint: http://100.102.32.69:3100/otlp

connectors:
  spanmetrics:
    dimensions:
      - name: http.method
      - name: http.status_code
      - name: http.route
      
processors:
  batch:

service:
  pipelines:
    metrics/spanmetrics:
      receivers: [spanmetrics]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [spanmetrics, otlp]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]